CC ?= cc
EXTRA_CFLAGS ?= -pipe -Os -Wall
COMPFLAGS = $(EXTRA_CFLAGS) -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_GNU_SOURCE -I.

COMMONDEFS = $(COMPFLAGS) -D_BSD_SOURCE -D_GNU_SOURCE

LDFLAGS ?= -s

DESTDIR ?=

PREDIR ?= /usr

BINDIR ?= $(PREDIR)/bin

LIBDIR ?= $(PREDIR)/lib

INCDIR ?= $(PREDIR)/include

DATADIR ?= $(PREDIR)/share

DOCDIR ?= $(DATADIR)/doc

STATIC ?= 0
